exclude: [README.md]
title: Yurii Zakharian
email: yuri-zakharyan@gmail.com
github: yzdxdydz
linkedin: yurii-zakharian
scholar_id: silHCQHr_UoC
description: >- # this means to ignore newlines until "baseurl:"
  To be description
baseurl: "" 
url: "https://yzdxdydz.github.io" 



# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown


